version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: opencve
      POSTGRES_USER: user
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  opencve:
    build: opencve/
    depends_on:
      - postgres
      - redis
    ports:
      - 8888:8888

volumes:
  redis_data:
    driver: local
  postgres-data:
    driver: local
